// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTLZeq9hR3JxTrjLv7BDIcbI6f5xoHars',
    appId: '1:17262262622:web:dc45fc1785fefa25f0b7cf',
    messagingSenderId: '17262262622',
    projectId: 'loginpage-dc917',
    authDomain: 'loginpage-dc917.firebaseapp.com',
    databaseURL: 'https://loginpage-dc917-default-rtdb.firebaseio.com',
    storageBucket: 'loginpage-dc917.appspot.com',
    measurementId: 'G-6Y40K3TXT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD38PNz-2LyzXkrn-1P_lKtYNjRP4Ts07Q',
    appId: '1:17262262622:android:9fa6a5582154af87f0b7cf',
    messagingSenderId: '17262262622',
    projectId: 'loginpage-dc917',
    databaseURL: 'https://loginpage-dc917-default-rtdb.firebaseio.com',
    storageBucket: 'loginpage-dc917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANbX7GM-VQaZ43k_yseafb2H8yiM-UN90',
    appId: '1:17262262622:ios:e17f46cb0595ff51f0b7cf',
    messagingSenderId: '17262262622',
    projectId: 'loginpage-dc917',
    databaseURL: 'https://loginpage-dc917-default-rtdb.firebaseio.com',
    storageBucket: 'loginpage-dc917.appspot.com',
    androidClientId: '17262262622-n7hjmn360dmp4l6do2ad7kp1g4t1rkov.apps.googleusercontent.com',
    iosClientId: '17262262622-ae8l2ont98gooh2rm6anmgim5k8uovuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonenuberlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANbX7GM-VQaZ43k_yseafb2H8yiM-UN90',
    appId: '1:17262262622:ios:4c4920523a1ad884f0b7cf',
    messagingSenderId: '17262262622',
    projectId: 'loginpage-dc917',
    databaseURL: 'https://loginpage-dc917-default-rtdb.firebaseio.com',
    storageBucket: 'loginpage-dc917.appspot.com',
    androidClientId: '17262262622-n7hjmn360dmp4l6do2ad7kp1g4t1rkov.apps.googleusercontent.com',
    iosClientId: '17262262622-ju9teflv7a4npvct0fivd2j8tatho1r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonenuberlogin.RunnerTests',
  );
}
